/**
 * Shared TypeScript types and JSON schemas for the Headless, Contract-First architecture.
 */

// Base properties shared across all canvas objects
export interface BaseFabricObject {
  id: string;
  type: string;
  left: number;
  top: number;
  width: number;
  height: number;
  angle: number;
  scaleX: number;
  scaleY: number;
  opacity: number;
  zIndex: number;
  /** Architect: Object Locking */
  locked?: boolean;
}

// Image object with distinct URLs for UI and Production
export interface ImageObject extends BaseFabricObject {
  type: 'image';
  /** Low-res, optimized URL used by UI-UX Agent for <200ms kinetic transitions */
  proxyUrl: string;
  /** 300 DPI, original quality URL used by Production Agent for 100% print accuracy */
  highResUrl: string;
  /** Final S3 uploaded path for strict backend synchronization */
  s3Url?: string;
  /** Maximum safe print dimensions calculated via DPI constraints */
  maxPrintWidth?: number;
  maxPrintHeight?: number;
  /** Flag for DPICalculator */
  qualityWarning?: boolean;
}

export interface TextObject extends BaseFabricObject {
  type: 'text';
  text: string;
  fontFamily: string;
  fontSize: number;
  fill: string;
  fontWeight: string | number;
  textAlign: 'left' | 'center' | 'right' | 'justify';
  /** Architect: Shrink-to-fit behavior */
  autoSize?: boolean;
  /** Architect: Font Loading Guard */
  isFontLoading?: boolean;
  /** Admin: Pre-mapped Placeholder Key from Template */
  placeholderKey?: string;
}

export interface PathObject extends BaseFabricObject {
  type: 'path';
  proxyUrl: string;
  highResUrl: string;
  s3Url?: string;
  isFontLoading?: boolean; // Inherit UI prop just in case it shares a loader
}

export type DesignLayerObject = ImageObject | TextObject | PathObject;

export interface DesignWarning {
  id: string;
  type: 'dpi' | 'bleed';
  message: string;
  objectId?: string;
}

// Represents an asset uploaded during this session
export interface SessionAsset {
  id: string;
  file: File | null; // null if persisting between sessions (we can't persist File)
  proxyUrl: string;
  status: 'uploading' | 'staged' | 'error';
  progress: number;
}

// Represents the global canvas/design state synchronized with OpenMage
export interface DesignState {
  /** Schema version to protect against breaking changes */
  version: string;
  /** Unique identifier matching the OpenMage backend */
  design_id: string;
  /** Real-time Base64 preview generated by Fabric Canvas */
  preview: string | null;
  /** Array of objects ordered by zIndex */
  objects: (ImageObject | TextObject | BaseFabricObject)[];
  /** Uploaded assets for the sidebar library */
  sessionAssets: SessionAsset[];
  /** Global warnings persisted across sessions */
  warnings: DesignWarning[];
  /** Global canvas width in pixels */
  canvasWidth: number;
  /** Global canvas height in pixels */
  canvasHeight: number;
  /** Background color hex */
  backgroundColor: string;
  /** Global safe zone margin for production print readiness */
  safeZoneMargin: number;
  /** Active object id selected in the canvas */
  activeObjectId?: string | null;
  /** Current brand for state isolation */
  brandId?: string | null;
  /** Floating Bounding box coordinates for Contextual UI */
  activeObjectBox?: { left: number, top: number, width: number, height: number } | null;
}

export interface OpenMageSystemMetadata {
  browser: string;
  timestamp: string;
  design_version: string;
}

export interface OpenMagePayload {
  design_id: string;
  system_metadata: OpenMageSystemMetadata;
  design_state: DesignState;
  is_orderable: boolean;
}
